/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoleCriteriaRouteImport } from './routes/role-criteria'
import { Route as PostingsRouteImport } from './routes/postings'
import { Route as ParametersRouteImport } from './routes/parameters'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as LinkedinPresenceRouteImport } from './routes/linkedin-presence'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleCriteriaRoute = RoleCriteriaRouteImport.update({
  id: '/role-criteria',
  path: '/role-criteria',
  getParentRoute: () => rootRouteImport,
} as any)
const PostingsRoute = PostingsRouteImport.update({
  id: '/postings',
  path: '/postings',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametersRoute = ParametersRouteImport.update({
  id: '/parameters',
  path: '/parameters',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedinPresenceRoute = LinkedinPresenceRouteImport.update({
  id: '/linkedin-presence',
  path: '/linkedin-presence',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/companies': typeof CompaniesRoute
  '/linkedin-presence': typeof LinkedinPresenceRoute
  '/outreach': typeof OutreachRoute
  '/parameters': typeof ParametersRoute
  '/postings': typeof PostingsRoute
  '/role-criteria': typeof RoleCriteriaRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/companies': typeof CompaniesRoute
  '/linkedin-presence': typeof LinkedinPresenceRoute
  '/outreach': typeof OutreachRoute
  '/parameters': typeof ParametersRoute
  '/postings': typeof PostingsRoute
  '/role-criteria': typeof RoleCriteriaRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/companies': typeof CompaniesRoute
  '/linkedin-presence': typeof LinkedinPresenceRoute
  '/outreach': typeof OutreachRoute
  '/parameters': typeof ParametersRoute
  '/postings': typeof PostingsRoute
  '/role-criteria': typeof RoleCriteriaRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/companies'
    | '/linkedin-presence'
    | '/outreach'
    | '/parameters'
    | '/postings'
    | '/role-criteria'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/companies'
    | '/linkedin-presence'
    | '/outreach'
    | '/parameters'
    | '/postings'
    | '/role-criteria'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/companies'
    | '/linkedin-presence'
    | '/outreach'
    | '/parameters'
    | '/postings'
    | '/role-criteria'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  CompaniesRoute: typeof CompaniesRoute
  LinkedinPresenceRoute: typeof LinkedinPresenceRoute
  OutreachRoute: typeof OutreachRoute
  ParametersRoute: typeof ParametersRoute
  PostingsRoute: typeof PostingsRoute
  RoleCriteriaRoute: typeof RoleCriteriaRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role-criteria': {
      id: '/role-criteria'
      path: '/role-criteria'
      fullPath: '/role-criteria'
      preLoaderRoute: typeof RoleCriteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postings': {
      id: '/postings'
      path: '/postings'
      fullPath: '/postings'
      preLoaderRoute: typeof PostingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parameters': {
      id: '/parameters'
      path: '/parameters'
      fullPath: '/parameters'
      preLoaderRoute: typeof ParametersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linkedin-presence': {
      id: '/linkedin-presence'
      path: '/linkedin-presence'
      fullPath: '/linkedin-presence'
      preLoaderRoute: typeof LinkedinPresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  CompaniesRoute: CompaniesRoute,
  LinkedinPresenceRoute: LinkedinPresenceRoute,
  OutreachRoute: OutreachRoute,
  ParametersRoute: ParametersRoute,
  PostingsRoute: PostingsRoute,
  RoleCriteriaRoute: RoleCriteriaRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
